import { PageHeader } from "@/components/layout/page-header";
import { ImportWizard } from "@/components/import/import-wizard";
import { listCategories } from "@/lib/data/categories";
import { isAiConfigured } from "@/lib/ai/client";
import { EmptyState } from "@/components/empty-state";
import { Sparkles } from "lucide-react";

export const metadata = { title: "Import Excel" };

export const dynamic = "force-dynamic";

/** Bulk import prompts from Excel with AI-generated metadata. */
export default async function ImportPage() {
  if (!isAiConfigured()) {
    return (
      <>
        <PageHeader title="Import Excel" />
        <EmptyState
          icon={Sparkles}
          title="AI is not configured yet."
          description="Bulk import generates metadata with an AI model. Set AI_API_KEY (and AI_BASE_URL, AI_MODEL) on the server to enable it."
        />
      </>
    );
  }

  const categories = await listCategories();

  return (
    <>
      <PageHeader
        title="Import Excel"
        description="Fill only the prompt_text column. Title, category, tags, and the rest are generated by AI and shown for review before anything is saved."
      />
      <ImportWizard categories={categories.map((c) => c.name)} />
    </>
  );
}
